### ISSUE TITLE
メニューウィンドウを使わない

### ISSUE THREAD

**Issue by masui** [masui/Gear#35]
キーやマウスホイールを操作したときGearのメニュー画面が出るようにしたい。

Greasemonkeyみたいなもので、ブラウザ画面上のカーソルイベントとマウスホイールイベントをフックできたらいいのだが...

**Comment by masui** [comment]
というのは苦しいからLinda利用する方が良いのか...?

**Comment by shokai** [comment]
メニューウィンドウをかなり細く（50pxぐらい）にしておいて、

- マウスが乗ったら幅400pxぐらいに大きくなる
- マウスがウィンドウ外に出たら細くなる

とか

**Comment by masui** [comment]
とりあえずそうしようと思いますがエレガントじゃないですな

**Comment by shokai** [comment]
:elephant:

**Comment by masui** [comment]
なんか面倒臭いし、我家では出しっぱなしでも問題ないのでとりあえず放置
